//Class that contains all of the questions and corresponding answers in parallel arrays. They will be called with a question object in a method of the main class.
class Questions {

    //Easy level questions for the next four below

    //Geography
    public String[] easyGeoQ = {"Which has the largest land area: Russia, China, or the U.S.? \n a) Russia \n b) China \n c) US \n", "What is the capital of Denmark? \n a) Madrid \n b) Copenhagen \n c) Warsaw", "The “Leaning Tower of Pisa” is located in which country? \n a) France \n b) Spain \n c) Italy", "Which of the following countries border Canada? \n a) Mexico \n b) Russia \n c) U.S.A", "Which is the world’s highest mountain? \n a) Kilimanjaro \n b) Mount Everest \n c) K2", "How many Great Lakes are there? \n a) Five \n b) Four \n c) Three", "The biggest desert in the world is . .? \n a) Arabian \n b) Sahara \n c) Great Australian", "Which of the following cities is not in Europe? \n a) Prague \n b) Barcelona \n c) Moscow", "The United Kingdom is comprised of how many countries? \n a) Six \n b) Five \n c) Four", "What is the imaginary line called that connects the north and south pole? \n a) Prime Meridian \n b) Prime Axis \n c) Lambert Line ", "Which U.S. state is the Grand Canyon located in? \n a) New Mexico \n b) Arizona \n c) Wyoming", " Which is the longest river in the world? \n a) Nile River \n b) Yellow River \n c) Amazon River", "What is the largest body of water? \n a) Indian Ocean \n b) Atlantic Ocean \n c) Pacific Ocean", "What is the smallest country, measured by total land area? \n a) Monaco \n b) Maldives \n c) Vatican City", "What is the approximate size of Earth’s equator? \n a) 40,000 km \n b) 50,000 km \n c) 25,000 km"};
    //geo answers
    public char[] easyGeoA = {'a', 'b', 'c', 'c', 'b', 'a', 'b', 'c', 'c', 'a', 'b', 'a', 'c', 'c', 'a'};

    //Entertainment
    String[] easyEntQ = {"Who played Jack in the acclaimed movie, Titanic? \n a) Ben Affleck  \n b) Leonardo Dicaprio \n c) Matt Damon", "Who played Allie in the movie, The Notebook? \n a) Rachel Weisz \n b) Rachel McAdams \n c) Jennifer Aniston", "How many seasons long is the famous sitcom, F.R.I.E.N.D.S? \n a) Four \n b) Ten \n c) Nine", "In 1997, director James Cameron won an Oscar for which blockbuster? \n a) Avatar \n b) The Terminator \n c) Titanic", "What 2018 film features the actor John Krasinski starring alongside his real-life wife Emily Blunt? \n a) The Office \n b) Us \n c) A Quiet Place", "Who are Harry’s best friends in the movie/book series, Harry Potter? \n a) Ron and Luna \n b) Hermione and Snape \n c) Ron and Hermione", "What animated character's catchphrase is \"To infinity, and beyond!\"? \n a) Zorak \n b) Space Ghost \n c) Buzz Lightyear", "In the film \"A Few Good Men\", which actor says the line - \"You can't handle the truth\" ? \na) Jack Nicholson \nb) Tom Cruise \nc) Kevin Bacon", "Complete this Patrick Swayze quote from the Dirty Dancing film - \"Nobody puts Baby in the …\"? \na) Dark \nb) Corner \nc) Spotlight", "\"You take the red pill--you stay in Wonderland, and I show you how deep the rabbit hole goes.\" is a quote from which film?\na) The Matrix \nb) X Men \nc) Star Wars", "The beautiful princess \"Sleeping Beauty\" falls asleep after pricking her finger on what item? \na) Sword \nb) Needle \nc) Spinning Wheel", "In which movie did Macaulay Culkin first play abandoned child Kevin McCallister? \na) Home Alone \nb) My Girl \nc) Richie Rich", "Which spinach-eating cartoon character was played by Robin William? \na) Mickey Mouse \nb) Velma \nc) Popeye", "Which crawling insects are the major stars of A Bug’s Life? \na) Beetles \nb) Caterpillars \nc) Ants", "Which 1994 movie was based on a TV cartoon and was set in Bedrock? \na) The Lion King\nb) Ace Ventura: Pet Detective\nc) The Flintstones"};
    //entertainment answers
    char[] easyEntA = {'b', 'b', 'b', 'c', 'c', 'c', 'c', 'a', 'b', 'a', 'c', 'a', 'c', 'c', 'c'};

    //History
    String[] easyHisQ = {"In which country are the ancient pyramids of Giza located? \na) Sudan \nb) Egypt\nc) Poland", "Who was the first American President?\na) Teddy Rosevelt \nb) Donald Trump \nc) George Washington", "Who was the first man to step on the moon? \na) Lance Armstrong \nb) Neil Patrick Harris \nc) Neil Armstrong", "Who is the Nobel Peace Prize named after? \na) Alfred Nobel \nb) Peter Griffin \nc) Mother Teresa", "Who wrote the play, Hamlet? \na) Eugene O’Neill \nb) Sophocles \nc) William Shakespeare", "Where did the ancient Olympic games originate? \na) France \nb) Germany \nc) Greece", "What are the Wright brothers famous for? \na) Delivering justice to criminals \nb) Building the first working bike. \nc) Inventing the airplane.", "What is the name of the first atomic bomb dropped on Hiroshima, Japan? \na) Little Boy \nb) Big Boy \nc) Alpha Strike A", "Who painted the ceiling of the Sistine Chapel? \na) Carol Williams \nb) Leonardo DaVinci \nc) Michaelangelo", "Which scientist invented the lightbulb? \na) Albert Einstein \nb) Nicola Tesla \nc) Thomas Edison", "Who was the writer of Alice’s Adventures in Wonderland? \na) Steven Hawking \nb) J.K. Rowling \nc) Lewis Caroll", "Which was the first country to use paper money? \na) Japan \nb) USA \nc) China", "Which document governs the United States? \na) Articles of Confederation \nb) Declaration of Independence\nc) The Constitution", "Which European country was on the selling end of the Louisiana purchase? \na) Portugal \nb) Britain \nc) France", "Who did the U.S. fight in the War of 1812? \na) Mexico \nb) Britain \nc) Spain"};
    //history answers
    char[] easyHisA = {'b', 'c', 'c', 'a', 'c', 'c', 'c', 'a', 'c', 'c', 'c', 'c', 'c', 'c', 'b'};

    //Science
    String[] easySciQ = {"What are the first three digits of pi? \na) 3.12 \nb) 3.14 \nc) 1.34", "Pneumonia affects which part of the human body? \na) Lungs \nb) Kidneys \nc) Heart", "Neurologists are doctors who diagnose and treat problems with what part of the human body? \na) Feet \nb) Brain \nc) Heart", "Who became the 1st woman to win a Nobel Prize, and the only woman to win in two different fields? \na) Marie Curie \nb) Rachel Carson \nc) Malala Yousafzai", "What is the third element on the periodic table? \na) H\nb) C  \nc) Li", "On which continent will you not find bees? \na) Asia \nb) Africa \nc) Antarctica", "What is the body's natural or acquired ability to resist certain diseases? \na) Immunity\nb) Independence\nc) Absolution", "What natural phenomena are measured by the Richter scale? \na) Tornadoes \nb) Tsunamis \nc) Earthquakes", "Who came up with the three laws of motion? \na) Richard Feynman \nb) Albert Einstein \nc) Isaac Newton", " What is the medical term for low blood sugar? \na) Hyperglycoma \nb) Hypotonia \nc) Hypoglycemia", "An animal that lives part of its life on land and part in water is known as what? \na) Turtles\nb) Amphibians \nc) Crocodiles", " The Earth’s air is comprised of what % of CO2? \na) 2% \nb) 70% \nc) 0.04%", " How much can an ant lift? \na) 10x its body weight \nb) 50x its body weight\nc) 100x its body weight", "What is the chemical formula for Ozone? \na) O2 \nb) CH3OH \nc) O3", "How many hearts does an octopus have? \na) 1 \nb) 8 \nc) 3"};
    //science answers
    char[] easySciA = {'b', 'a', 'b', 'a', 'c', 'c', 'a', 'c', 'c', 'c', 'b', 'c', 'b', 'c', 'c'};

    //Hard level questions below
    //Geography
    String[] hardGeoQ = {"Which nation has the smallest land area, less than one-fifth of a square mile? \na) Madagascar \nb) Malaysia \nc) Vatican City", "What is the southernmost territory of the U.S.? \na) Hawaii \nb) American Samoa \nc) Puerto Rico", " Which of these cities is farthest north of the equator: Berlin, Germany; London, England; or Toronto, Ontario? \na) Berlin \nb) London \nc) Toronto", "Which of the Great Lakes has the smallest area? \na) Lake Erie \nb) Lake Michigan \nc) Lake Superior", "Which country was not part of Mesopotamia? \na) Turkey \nb) Greece \nc) Iraq", "Which U.S. state has the longest coastline? \na) Hawaii \nb) Alaska \nc) California", "After the U.S., which nation boasts the greatest number of Internet users? \na) China\nb) Canada \nc) Japan", "Which nation’s flag consists of a plain green field, without symbols or other colors? \na) Scotland\nb) Greenland \nc) Libya", "What is the most common national ancestry claimed by American citizens? \na) Irish\nb) Italian\nc) German", " Which country was the world’s top tourist destination in 2007?\na) France\nb) Costa Rica\nc) Italy", " Which country was the world’s top tourist destination in 2007?\na) France\nb) Costa Rica\nc) Italy", "What province in Canada has a flag depicting a yellow sun?\na) BC\nb) PEI\nc) NS", "What city is famous for the 1849 gold rush?\na) Mississippi City\nb) Little Rock\nc) Sacramento", "What province in Canada has the highest crime rate?\na) Manitoba \nb) Nunavut\nc) Ontario", "What is the most populated city in the world - with a population of 24 million?\na) Shanghai\nb) Beijing\nc) Karachi"};
    char[] hardGeoA = {'c', 'b', 'a', 'a', 'b', 'b', 'a', 'c', 'c', 'a', 'b', 'a', 'c', 'b', 'a'};

    //Entertainment
    String[] hardEntQ = {"Which sitcom won the Best Comedy Emmy award five years in a row, from 1994-98? \na) Frasier\nb) Seinfeld\nc) Fresh Prince of Bel-Air", "Which television show won the Best Comedy Emmy award the last two years (2007-08)? \na) Big Bang Theory\nb) 30 Rock\nc) How I Met Your Mother", "Who is the most recent American to have won the Nobel Prize in Literature? \na) Margaret Atwood\nb) John Green\nc) Toni Morrison", "Who is the only singer to have won back-to-back Record of the Year Grammy awards, for “The First Time Ever I Saw Your Face” and “Killing Me Softly with His Song”? \na) Roberta Flack\nb) Celine Dion\nc) Joni Mitchel", "What is the longest-running Broadway show? \na) Cats\nb) Phantom of the Opera\nc) Wizard of Oz", " Jack Nicholson has won three Oscars; he has been nominated for a dozen. For which films did he win?\na) As Good as It Gets , Terms of Endearment , One Flew Over the Cuckoo’s Nest \nb) Ghost, As Good as It Gets , Terms of Endearment\nc) Terms of Endearment , One Flew Over the Cuckoo’s Nest", "For which movie did Martin Scorsese win his first Best Director Academy Award?\na) The Departed\nb) The Dark Knight\nc) The Titanic", "Name the two top-selling albums of all-time in the U.S. \na) Eagles/ Their Greatest Hits, Thriller \nb) Thriller, The Wall\nc) Queen, Thriller", " What was the best-selling newspaper in the United States in 2008? \na) USA Today\nb) New York Times\nc) The Post", "What was the most popular musical genre for commercial radio stations in the U.S. in 2008? \na) Country \nb) R&B \nc) Pop", "What U.S. magazine has the highest paid circulation? \na) AARP \nb) People\nc) Oprah", "What is the single highest-rated television episode in U.S. history, with more than 50 million households tuned in? \na) Final episode of Friends \nb) Final episode of the Cosby Show\nc) Final episode of M.A.S.H.", "In the 2007-08 U.S. TV season, what was the top-rated show?\na) America’s Got Talent\nb) American Idol\nc) Hell’s Kitchen", "What is the most sold video game of all time?\na) Minecraft\nb) Tetris\nc) Grand Theft Auto 5", "What was Leonardo DiCaprio’s first film? \na) Titanic \nb) Critters 3\nc) Over the Hedge"};
    char[] hardEntA = {'a', 'b', 'c', 'a', 'b', 'a', 'a', 'a', 'a', 'a', 'a', 'c', 'b', 'b', 'b'};

    //History
    String[] hardHisQ = {"Which Pope reigned the earliest? \na) Clement XIV \nb) Pius X \nc) Innocent XII", "English physician Edward Jenner famously invented the vaccination for what disease? \na) Smallpox \nb) Polio \nc) Mumps", "Known as the founder of modern nursing, Florence Nightingale became prominent while serving during which conflict? \na) World War I \nb) Crimean War \nc) World War II", "Henry VII belonged to which royal house? \na) Stuart \nb) Windsor \nc) Tudor", "Considered a heroine of France, how is Joan of Arc also known? \na) Maid of Orleans\nb) Saviour of Orleans\nc) Mother of Orleans", "How many stones make up the prehistoric monument \"Stonehenge\"? \na)120 \nb)80 \nc)60", "The ivory-white marble mausoleum \"Taj Mahal\" was constructed in which century? \na) 18th \nb) 19th \nc) 17th", "Henry McCarty was the real name of which American Old West gunfighter? \na) Billy the Kid \nb) Kid Curry \nc) Wild Bill", "Which of these historic events happened BEFORE the others? \na) Treaty of Tordesillas \nb) Hundred Years War Ends \nc) Battle of Bosworth", "Which singer made his debut in the film \"Love Me Tender\" in 1956? \na) Elvis Presley \nb) Ricky Nelson \nc) Frank Sinatra", "In what year did Charles Lindbergh makes his trans-Atlantic flight? \na) 1933 \nb) 1907 \nc) 1927", "When did Michelangelo start painting the ceiling of the Sistine Chapel? \na) 1464 \nb) 1832 \nc) 1508", "When did Mount Pelee erupt? \na) 1902 \nb) 1803 \nc) 1765", "When did John Adams, the second President of the United States, take office? \na) 1689 \nb) 1836 \nc) 1797", "Which British monarch holds the record for the longest reign? \na) King Henry VIII \nb) William of Orange \nc) Queen Victoria"};
    char[] hardHisA = {'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'a', 'c', 'c', 'a', 'c', 'c'};

    //Science -- hard section
    String[] hardSciQ = {"What is the conversion rate from Lbs to Kg? \na) 1.6 \nb) 2.2 \nc) 0.2", "What is the 23rd digit of pi? \na) 4 \nb) 8 \nc) 5", "\"Apiology\" is the scientific study of what? \na) Trout \nb) Honey Bees \nc) Earthquakes", "Which of the following elements has the lowest atomic mass? \na) Chlorine \nb) Neon \nc) Silicon", "The \"Greater Siren\" is a type of which animal? \na) Toad \nb) Frog \nc) Salamander", "Who is credited for having discovered the \"Law of Refraction\" in 1621? \na) Robert Boyle \nb) Willebrord Snellius \nc) Alfred Wallace", "The medical specialty field of \"Angiology\" deals with what diseases? \na) Circulatory \nb) Digestive \nc) Respiratory", "Brass is a metallic alloy that is made from copper and what other chemical element? \na) Lead \nb) Zinc \nc) Iron", "Nicolaus Copernicus believed that the size of each planet's orbit depended on its distance from what? \na) Sun \nb) Earth \nc) North star", "In 2001, a physicist named John Keogh used a loophole in Australian law to patent a \"circular transportation facilitation device\". By what name is this device usually known? \na) Perpetual motion machine \nb) Wheel \nc) Bicycle", "Who reportedly shouted \"Eureka!\" when his bath revealed the secret to finding an object's density?\na) Pythagoras \nb) Socrates \nc) Archimedes", "By applying an electric current to dead frogs' legs, I got the legs to twitch, and became convinced that this \"animal electricity\" was its life force. Who am I? \na) Luigi Galvani \nb) Alessandro Volta \nc) Thomas Edison", "The first astronauts were military test pilots. Who was the first US civilian in space? \na) Jake Garn \nb) Neil Armstrong \nc) Harrison Schmitt", "Aside from the fact that it's a flying saucer, what else is unusual about a spy plane called the DarkStar? \na) It has no pilot \nb) It can reach the Moon \nc) It can become invisible under certain conditions", "When the Montgolfier brothers launched their first balloon, whom or what was it carrying? \na) A duck \nb) A rooster \nc) A duck, rooster, and sheep"};
    char[] hardSciA = {'b', 'a', 'b', 'b', 'c', 'b', 'a', 'b', 'a', 'b', 'c', 'a', 'b', 'a', 'c'};
}
